#!/bin/bash
inotifywait -m /etc/passwd  -e modify,attrib,close_write,move,create,delete  |
    while read path action file; do
        curl -X POST --data-urlencode 'payload={"text": "'"$file"' has been modified '"$path"' on '"$HOSTNAME"'."}' https://hooks.slack.com/services/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
        echo "The file '$file' appeared in directory '$path' via '$action'"
    done
